apiVersion: v1
kind: Pod
metadata:
  name: orders-api
  namespace: orders-restricted
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: api
      image: registry.k8s.io/pause:3.9
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: [ALL]
